[package]
name = "igd-studio/my-singing-fish"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

bridgenet2 = "ffrostflame/bridgenet2@0.5.6"
promise = "evaera/promise@4.0.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"
camerashaker = "brittonfischer/camerashaker@0.1.0"
iris = "sirmallard/iris@2.4.1"
slidermodule = "aerodymier/slidermodule@0.2.4"